[menu]
executable = 'rofi'
args = [
    '-theme', '~/.config/rofi/style_1.rasi',
    '-dmenu',
    '-show-icons',
    '-markup-rows',
    '-mesg', '{prompt}',
    '-i',
    '-p', '{prompt}',
    '-l', '6',
]

[format]
window_format = "{urgency_start}<b>“{title}”</b>{urgency_end} — <i>{app_name}</i> on workspace {workspace_name}   <span alpha='20000'>({id})</span>\u0000icon\u001f{app_icon}"
workspace_format = '<b>Workspace {name}</b>   <span alpha="20000">({id})</span>'
urgency_start = '<span background="darkred" foreground="yellow">'
urgency_end = '</span>'
html_escape = true
icon_dirs = [
    '/usr/share/icons/hicolor/scalable/apps',
    '/usr/share/icons/hicolor/48x48/apps',
    '/usr/share/pixmaps',
]
fallback_icon = '/usr/share/pixmaps/archlinux-logo.png'

[layout]
auto_tile = false
auto_tile_min_window_width_per_output_width = [
    [
    1024,
    500,
],
    [
    1280,
    600,
],
    [
    1400,
    680,
],
    [
    1440,
    700,
],
    [
    1600,
    780,
],
    [
    1920,
    920,
],
    [
    2560,
    1000,
],
    [
    3440,
    1000,
],
    [
    4096,
    1200,
],
]
