# Inserts a blank line between shell prompts
#add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
#[character] # The name of the module we are configuring is "character"
#:was = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

format = """
[î‚¶](fg:#94348E)\
$username\
$sudo\
$directory\
(â†“ Source control - for right side â†“)\
$git_metrics\
$git_commit\
$git_branch\
$git_status\
(â†‘ Source control - for right side â†‘)\
(â†“ Toolchain version modules â†“)\
$docker_context\
$php\
$python\
$rust\
(â†“ Toolchain version modules â†“)\
$character\
$time\
[î‚° ](fg:#464347)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_root = "bold bg:#9A348E fg:#FF5511"
style_user = "bg:#9A348E fg:#EEEEEE"
format = "[[ ](bg:#9A348E fg:#464347)$user[î‚°](bg:#464347 fg:#9A348E)]($style)"

[sudo]
style = "bold green bg:#9A348E"
symbol = "ğŸ‘© "
disabled = false

[directory]
style = "bg:#DA627D"
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[[î‚°](bg:#DA627D fg:#464347)$path[î‚°](bg:#464347 fg:#DA627D)]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_branch]
symbol = "ğŸŒ± "
style = "bg:#FCA17D"
format = '[[ $symbol $branch ](bg:#FCA17D)]($style)'
truncation_length = 4
truncation_symbol = ""
ignore_branches = ["master", "main"]

[git_status]
style = "bg:#FCA17D fg:#fff"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨ ${count}"
behind = "ğŸ˜° ${count}"
diverged = "ğŸ˜µ ${count}"
up_to_date = "âœ“ ${count}"
untracked = "ğŸ¤· ${count}"
stashed = "ğŸ“¦ ${count}"
modified = "ğŸ“ ${count}"
staged = '[++\($count\)](green bg:#FCA17D)'
renamed = "ğŸ‘… ${count}"
deleted = "ğŸ—‘ ${count}"
format = "[[î‚°](bg:#FCA17D fg:#464347)[( $all_status$ahead_behind )](bold bg:#FCA17D)[î‚°](bg:#464347 fg:#FCA17D)]($style)"

[git_metrics]
added_style = "bold blue bg:#FCA17D"
format = '[$added]($added_style)/[-$deleted]($deleted_style)'

[python]
# disabled = true
symbol = "î˜† "
style = "bg:#EBD45B fg:#111111"
# pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[[î‚°](fg:#464347 bg:#EBD45B)$symbol$pyenv_prefix$version(\($virtualenv\))[î‚°](bg:#464347 fg:#EBD45B)]($style)'
[rust]
symbol = "ğŸ¦€"
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[î‚°](fg:#464347 bg:#33658A)[ ğŸ§ $time ](bg:#33658A)[î‚°](bg:#464347 fg:#33658A)]($style)'

[character]
success_symbol = "[âœ“](bold green bg:#33658A)"
error_symbol = "[âœ—](bold red bg:#33658A)"
format = '[[î‚°](fg:#464347 bg:#33658A)[ $symbol ](bg:#33658A)[î‚°](bg:#464347 fg:#33658A)]($style)'

