# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/
backend: Clipboard
fast_inject: true

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ";mail"
    replace: "lorenzo.carbonell.cerezo@gmail.com"

  - trigger: ";ja"
    replace: "ğŸ˜‚ğŸ˜‚ğŸ˜‚ğŸ˜‚ğŸ˜‚ğŸ˜‚"

  - trigger: ";oh"
    replace: "ğŸ˜±"

  - trigger: ";caca"
    replace: "ğŸ’©"

  - trigger: ";uhm"
    replace: "ğŸ¤”"

  - trigger: ";ssh"
    replace: "ğŸ¤«"

  - trigger: ";zzz"
    replace: "ğŸ¥± ğŸ˜´"

  - trigger: ";espanso"
    replace: "Hi there!!!"

  - trigger: ";fix"
    replace: "ğŸ›"

  - trigger: ";feature"
    replace: "âœ¨"

  - trigger: ";update"
    replace: "âš¡ï¸"

  - trigger: ";doc"
    replace: "ğŸ“š"

  - trigger: ";ic"
    replace: "`$|$`"

  # Dates
  - trigger: ";fecha"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # Shell commands
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Forms
  - trigger: ";test"
    form: |
      Hola {{campeÃ³n}},
      Esto es una prueba

  - trigger: ";a"
    form: "<a href=\"{{url}}\">{{web}}</a>"

  - trigger: ";form"
    form: |
      {{opciones}}
    form_fields:
      opciones:
        type: choice
        values:
          - Primera opciÃ³n
          - Segunda opciÃ³n

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
    - name: output
      type: shell
      params:
        cmd: "curl 'https://api.ipify.org'"

