# Inserts a blank line between shell prompts
#add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
#[character] # The name of the module we are configuring is "character"
#:was = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
#[package]
#î‚¶disabled = true

format = """
[î‚°](bg:#464347 fg:#625d63)\
$sudo\
$directory\
(â†“ Source control - for right side â†“)\
$git_metrics\
$git_commit\
$git_branch\
$git_status\
(â†‘ Source control - for right side â†‘)\
(â†“ Toolchain version modules â†“)\
$docker_context\
$php\
$python\
$rust\
(â†“ Toolchain version modules â†“)\
(â†“ on input line â†“)\
$time\
[î‚´](fg:#464347)\
$line_break\
[î‚°](bg:#464347 fg:#625d63)\
$jobs\
$cmd_duration\
$status\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_root = "bold bg:#9A348E fg:#FF5511"
style_user = "bg:#9A348E fg:#EEEEEE"
format = "[[î‚°](bg:#9A348E fg:#464347)$user[î‚°](bg:#464347 fg:#9A348E)]($style)"

[sudo]
style = "bold green bg:#9A348E"
symbol = "ğŸ‘© "
disabled = false

[cmd_duration]
# disabled = true
style = "bg:#625d63 fg:#FBDE2D"
min_time = 2_000
show_milliseconds = true
show_notifications = false
min_time_to_notify = 45_000
format = "[[î‚°](bg:#625d63 fg:#464347) â±ï¸ $duration[î‚°](bg:#464347 fg:#625d63)]($style)"

[directory]
style = "bg:#DA627D fg:#111111"
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[[î‚°](bg:#DA627D fg:#464347)$path[î‚°](bg:#464347 fg:#DA627D)]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_commit]
commit_hash_length = 11
tag_symbol = "ğŸ”– "

[git_branch]
symbol = "ğŸŒ±"
style = "bg:#FCA17D fg:#111111"
truncation_length = 11
truncation_symbol = ""
ignore_branches = ["master", "main"]
format = "[[î‚°](bg:#FCA17D fg:#464347)( $symbol$branch )[î‚°](bg:#464347 fg:#FCA17D)]($style)"

[git_status]
style = "bg:#FCA17D fg:#111111"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨ ${count}"
behind = "ğŸ˜° ${count}"
diverged = "ğŸ˜µ ${count}"
up_to_date = "âœ“ ${count}"
untracked = "ğŸ¤· ${count}"
stashed = "ğŸ“¦ ${count}"
modified = "ğŸ“ ${count}"
staged = "++ ${count}"
renamed = "ğŸ‘… ${count}"
deleted = "ğŸ—‘ ${count}"
format = "[[î‚°](bg:#FCA17D fg:#464347)( $all_status$ahead_behind )[î‚°](bg:#464347 fg:#FCA17D)]($style)"

[git_metrics]
added_style = "bold blue bg:#FCA17D"
format = '[$added]($added_style)/[-$deleted]($deleted_style)'

[jobs]
# disabled = true
symbol = " ï€º "
style = "bold bg:#625d63 fg:#FFA200"
# threshold = 1
format = "[$symbol$number]($style)"


[line_break]
disabled = false

[python]
# disabled = true
symbol = " î˜† "
style = "bg:#EBD45B fg:#111111"
# pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[[î‚°](fg:#464347 bg:#EBD45B)$symbol$pyenv_prefix$version(\($virtualenv\))[î‚°](bg:#464347 fg:#EBD45B)]($style)'

[php]
symbol = " ğŸ˜ "
style = "bg:#4D588E fg:#EEEEEE"
format = "[[î‚°](bg:#4D588E fg:#464347)$symbol$version[î‚°](bg:#464347 fg:#4D588E)]($style)"

[rust]
symbol = " ğŸ¦€ "
style = "bg:#ffb347 fg:#464347"
format = "[[î‚°](bg:#ffb347 fg:#464347)$symbol$version[î‚°](bg:#464347 fg:#ffb347)]($style)"

[status]
# disabled = false
symbol = "ï„ª"
style = "bg:#464347 fg:#ff3322"
format = "[$symbol$status]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A fg:#111111"
format = '[[î‚°](fg:#464347 bg:#33658A) ğŸ§ $time [î‚°](bg:#464347 fg:#33658A)]($style)'

[character]
success_symbol = "[[î‚°](bg:#AFD700 fg:#464347)î‚°](fg:#AFD700)"
error_symbol = "[[î‚°](bg:#ff3322 fg:#464347)î‚°](fg:#ff3322)"
vicmd_symbol = "[[î‚°](bg:#6f6a70 fg:#464347)î‚³[î‚°](bg:#464347 fg:#6f6a70)](bold bg:#6f6a70 fg:#ff3322)"
format = "[[](bg:#464347)$symbol ]($style)"

[docker_context]
disabled = false
style = "bg:#33658A fg:#111111"
format = '[[î‚°](fg:#464347 bg:#33658A) $symbol[î‚°](bg:#464347 fg:#33658A)]($style)'

